# Generated by Django 4.2.7 on 2023-11-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_type',
        ),
    ]
