# Generated by Django 4.2.7 on 2023-11-09 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0002_remove_customer_id_number_remove_customer_id_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='drivers_license',
            new_name='drivers_license_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='selected_car',
            new_name='select_car',
        ),
        migrations.AddField(
            model_name='customer',
            name='checkin_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
