# Generated by Django 4.2.7 on 2023-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0005_rename_drivers_license_number_customer_drivers_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
