# Generated by Django 4.2.7 on 2023-11-11 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0007_rename_model_name_car_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='select_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkIn.car'),
        ),
    ]
